version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8433:433"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    networks:
      - nginx-network

  nginx-service:
    image: nginx-service:latest
    ports:
      - "8081:8081"
    networks:
      - nginx-network

networks:
  nginx-network: